### ISSUE TITLE
Internal Hash Map vs. Returning Handles?

### ISSUE THREAD

**Issue by KevinTyrrell** [adtac/hollow-heap#1]
Currently it seems like your heap enforces the `O(1)` decrease key because it `returns` a `HANDLE` of the location of where the node is stored once it is placed into the tree. 

Did you consider instead having a Hash Map which associates the data -> location in the heap? That way, when the data is inserted, the hash map automatically knows where it lies in the heap? 

I'm curious to hear your thoughts on that. 

PS: Why is the declaration and implementation combined in your files? Should be `.h` for declarations and `.cpp` for implementation, no?

**Comment by adtac** [comment]
By a hash map, do you mean hashing the key? If so, I have a couple of questions:

 - What happens when you try to insert two items with the same key? They would both hash to the same result, creating a clash. We can use something like chaining to solve this, but it's probably a performance hit.
 - IMO the location in the tree is an excellent "hash" value for each node. It can act as a handle with zero computation when it's passed back to us, it is unique, and it requires zero computation when it's created.

I'm afraid I don't really see any benefit in hashing the node's key to return a handle. Maybe I'm missing something, can you expand a bit more on that?

>PS: Why is the declaration and implementation combined in your files? Should be .h for declarations and .cpp for implementation, no?

Heh, I never expected anyone to come across this repo (out of curiosity, how did you find it?). The code is far from "ready", whatever that is. I'm still experimenting with optimizations (I'm working on a research paper on hollow heaps), so I didn't pay much attention to code standards. Eventually, before I release it, I want to separate the implementation from the declaration, document the functions better, add a couple of more realistic tests, document the optimizations, and stuff.

Thanks for the taking a look at the code! :) Also, apologies for the late response; I must have forgot to watch the repo, so I didn't get any notification.

**Comment by KevinTyrrell** [comment]
So I'm actually implementing my own Fibonacci Heap as part of [my collections library](https://github.com/KevinTyrrell/C-DataStructures) that I'm making for the C programming language. I haven't posted the Fibonacci Tree code there yet until I solve this `decrease key` complexity issue that I'm having. Since Fibonacci Trees and Hollow Heaps are very similar, I felt like perhaps you might have some ideas regarding it.
When I was implementing it originally, I thought about the idea you went with (returning the `Node` associated with the key that the user provides). Then I thought that would not be good, since now you are breaking levels of abstraction. Making it a `void*` `HANDLE` esque thing definitely solves that. However, now the user has to hold onto all these `HANDLE`s and will probably end up creating a map to store them in anyways. 
If the tree itself had an internal map, whenever a node is inserted or removed from the heap, the map must be updated (O(1) overhead). The key of the map would be a different type of `Node` which only has a data element and a `next` pointer. There should never be a situation where we must iterate over that linked list. 
So for example, let's say the user wants to insert `'A'`. `A` gets hashed to an index, a `Node` of `(A)->NULL` is created and is put inside the hash map. The value associated with that `A` is the `heap node` which lies inside of the heap. This means there's no need for `HANDLE`s. If the user wants to add `A` again, we check if `map.contains('A')` which will return true. We grab that element `(A)->NULL` and then append the duplicate, which now looks like `(A)->(A)->NULL`. If the user says `heap.remove('A')` then we delete the `head` of the Linked list and replace it with its right neighbor.

It seems like a lot of work and it might be... however there are some benefits.
If you use a map, then `heap.contains()` becomes `O(1)` instead of `O(n)`. I'm pretty sure right now your heap would take `n` time to check if an element exists right? If they happen to lose the `HANDLE` and want to `decrease key`, it would take `O(n)` time to find the element to decrease it as well. The map would make that impossible and it would be `O(1)`.

Here's the thing though... are you familiar with the `union` operation? It combines two heaps together and returns the result. If you used a backing hash map, you can combine the heaps in `O(1)` but the combine the maps together would take `O(n)`. That's the really bad part.

So basically the trade offs are 
bad: Hashing overhead on `insert` and `delete`
bad: double the memory requirement because of the map
bad: `union` goes from `O(1)` to `O(n)`
bad: user must provide a way to `hash` his keys
good: user no longer needs to use `HANDLE` variables
good: `contains` goes from `O(n)` to `O(1)`

What do you think? Am I missing something? It may not be worth it but I thought backing it with a hash map was an interesting idea. It certainly adds a lot of overhead though.

And no worries. My professors when I first learned coding were very strict on documentation and good project structure so now I always make a `.cpp/.c` and associated `.h` file right away. Declare in the `.h` and define in the `.cpp/.c` so I don't have to do it later. I haven't done enough C++ to really understand why to use `.hpp` over `.h`. Is there an advantage?

I found your repo from reddit. The user who linked it to me likely did a google search or stumbled upon it himself.

**Comment by adtac** [comment]
>So I'm actually implementing my own Fibonacci Heap as part of [my collections library](https://github.com/KevinTyrrell/C-DataStructures) that I'm making for the C programming language. I haven't posted the Fibonacci Tree code there yet until I solve this `decrease key` complexity issue that I'm having. Since Fibonacci Trees and Hollow Heaps are very similar, I felt like perhaps you might have some ideas regarding it.
>When I was implementing it originally, I thought about the idea you went with (returning the `Node` associated with the key that the user provides). Then I thought that would not be good, since now you are breaking levels of abstraction. Making it a `void*` `HANDLE` esque thing definitely solves that. However, now the user has to hold onto all these `HANDLE`s and will probably end up creating a map to store them in anyways.

Ah, that was before I moved on to an array-based model. With this, the memory is pre-allocated and the performance improvements are much more pronounced. I haven't pushed the commits yet.

With the array-based model, handles are `unsigned int`s.

>If the tree itself had an internal map, whenever a node is inserted or removed from the heap, the map must be updated (O(1) overhead). The key of the map would be a different type of `Node` which only has a data element and a `next` pointer. There should never be a situation where we must iterate over that linked list. 
>So for example, let's say the user wants to insert `'A'`. `A` gets hashed to an index, a `Node` of `(A)->NULL` is created and is put inside the hash map. The value associated with that `A` is the `heap node` which lies inside of the heap. This means there's no need for `HANDLE`s. If the user wants to add `A` again, we check if `map.contains('A')` which will return true. We grab that element `(A)->NULL` and then append the duplicate, which now looks like `(A)->(A)->NULL`. If the user says `heap.remove('A')` then we delete the `head` of the Linked list and replace it with its right neighbor.

Ah, now I understand what you mean.

One thing: it *is* the job of the user to keep track of handles. They don't necessarily need a map from item to handle - the handle itself could be an ID. Maintaining a map internally isn't the purpose of the heap.

However, what you mention is definitely useful. But I don't think that belongs in the implementation of the heap itself. It could be a wrapper around a heap, resulting in a custom-data structure that does what you said. This wrapper could easily be adapted to *any* heap, thereby removing the dependence on the heap. With that you can switch out hollow heaps for fibonacci heaps and still have your custom-data structure work instead of having to implement the map-thingy all over again in a fibonacci heap.

>It seems like a lot of work and it might be... however there are some benefits.
If you use a map, then `heap.contains()` becomes `O(1)` instead of `O(n)`. I'm pretty sure right now your heap would take `n` time to check if an element exists right? If they happen to lose the `HANDLE` and want to `decrease key`, it would take `O(n)` time to find the element to decrease it as well. The map would make that impossible and it would be `O(1)`.

>Here's the thing though... are you familiar with the `union` operation? It combines two heaps together and returns the result. If you used a backing hash map, you can combine the heaps in `O(1)` but the combine the maps together would take `O(n)`. That's the really bad part.

Don't hollow heaps support heap union in O(1)? You just need to link the two heaps' roots. Heap order is preserved automatically.

Admittedly, this won't work with an `unsigned` handle in the array-based model (because it's not unique). But this is pretty easy to overcome - instead of an `unsigned` handle, return `base_addr + the_unsigned_integer` as the handle. This is guaranteed to be unique for each heap.

However, the pointer-based model's union operation would still be O(1) (even if I haven't implemented the method yet).

> So basically the trade offs are 
> bad: Hashing overhead on `insert` and `delete`
> bad: double the memory requirement because of the map
> bad: `union` goes from `O(1)` to `O(n)`
> bad: user must provide a way to `hash` his keys
> good: user no longer needs to use `HANDLE` variables
> good: `contains` goes from `O(n)` to `O(1)`

>What do you think? Am I missing something? It may not be worth it but I thought backing it with a hash map was an interesting idea. It certainly adds a lot of overhead though.

I still think this should be a wrapper around heaps, not built into the heaps themselves. As I said, with a wrapper custom data structure, you can simply swap out heaps as you like.
